name: task7_database_usage
description: "Cognifyz Internship - Task 7: Basic Database Usage (Level 4 - Expert)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: '>=6.0.0'
  sqflite: '>=2.0.0'
  path: '>=1.8.0'
  sqflite_common_ffi_web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=3.0.0'

flutter:
  uses-material-design: true
